<?php

namespace Petramas\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LiquidacionMaterialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LiquidacionMaterialRepository extends EntityRepository
{
}
