<?php

namespace Petramas\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RecepcionMaterialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecepcionMaterialRepository extends EntityRepository
{
}
