<?php

namespace Petramas\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BoletaRecepcionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoletaRecepcionRepository extends EntityRepository
{
}
