<?php

namespace Petramas\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LiquidacionMaterialDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LiquidacionMaterialDetalleRepository extends EntityRepository
{
}
