<?php

namespace Petramas\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PedidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidoRepository extends EntityRepository
{
    public function findPedidosDeUsuarioPorEstado($id, $estado)
    {
        $query = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('p')
            ->from('PetramasMainBundle:Pedido', 'p')
            ->innerJoin('p.cliente','c')
            ->innerJoin('c.usuario','u')
            ->where('u.id = :cliente_id')->setParameter('cliente_id', $id)
            ->andWhere('p.estado = :estado_id')->setParameter('estado_id', $estado)
            ->getQuery();
        
        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
