security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_CLIENTE: ROLE_CLIENTE
        ROLE_ADMIN: [ROLE_USER, ROLE_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                always_use_default_target_path: true
                login_path: /login
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: /
                use_referer: true
                target_path_parameter: _target_path
                failure_path: /login
            logout:
                path: /logout
                target: /login
                invalidate_session: false
            anonymous: true
            remember_me:
                key: %secret%
                lifetime: 3600
                path: /login
                domain: local.petramas.com
                user_provider: fos_userbundle

    access_control:
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY } 
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: IS_AUTHENTICATED_FULLY }
